// Theme definitions
export const THEMES = {
  light: {
    bg: '#fff',
    bgAlt: '#FAFAFA',
    text: '#000',
    textSecondary: '#666',
    textMuted: '#999',
    textFaint: '#bbb',
    textFaintest: '#ccc',
    border: '#F0F0F0',
    borderLight: '#F5F5F5',
    accent: '#000',
    accentText: '#fff',
    hover: '#FAFAFA',
    ring: '#F0F0F0',
    gridEmpty: '#F5F5F5',
    gridLow: '#ddd',
    gridMid: '#888',
    gridHigh: '#000',
  },
  dark: {
    bg: '#0a0a0a',
    bgAlt: '#111',
    text: '#fff',
    textSecondary: '#aaa',
    textMuted: '#777',
    textFaint: '#555',
    textFaintest: '#444',
    border: '#1a1a1a',
    borderLight: '#151515',
    accent: '#fff',
    accentText: '#000',
    hover: '#151515',
    ring: '#222',
    gridEmpty: '#151515',
    gridLow: '#333',
    gridMid: '#666',
    gridHigh: '#fff',
  }
};

// Generate styles based on theme
export const getStyles = (t) => ({
  pageWrapper: { display: 'grid', gridTemplateColumns: '280px 1fr 280px', minHeight: '100vh', background: t.bg, color: t.text, fontFamily: "'Instrument Sans', system-ui, sans-serif" },
  leftPanel: { padding: '48px 32px', borderRight: `1px solid ${t.border}`, display: 'flex', flexDirection: 'column', overflow: 'hidden', background: t.bg },
  container: { padding: '48px 80px 64px', minHeight: '100vh', background: t.bg, color: t.text, fontFamily: "'Instrument Sans', system-ui, sans-serif" },
  rightPanel: { padding: '48px 32px', borderLeft: `1px solid ${t.border}`, background: t.bg },
  tabs: { display: 'flex', gap: 48, marginBottom: 64 },
  tab: { fontSize: 15, color: t.textFaint, cursor: 'pointer', border: 'none', background: 'none', fontFamily: 'inherit', fontWeight: 400, padding: 0 },
  tabActive: { color: t.text },
  dateHeader: { textAlign: 'center', marginBottom: 56 },
  monthYear: { fontSize: 14, letterSpacing: '0.25em', textTransform: 'uppercase', color: t.textMuted, marginBottom: 16 },
  dayNumber: { fontSize: 200, fontWeight: 100, lineHeight: 0.8, position: 'relative', display: 'inline-block', color: t.text },
  strikeX: { position: 'absolute', top: '50%', left: '50%', width: '110%', height: 3, background: t.accent, transition: 'transform 300ms ease-out, opacity 300ms ease-out' },
  dayOfWeek: { fontSize: 14, letterSpacing: '0.25em', textTransform: 'uppercase', color: t.textMuted, marginTop: 16 },
  navArrow: { fontSize: 36, fontWeight: 100, color: t.textFaintest, cursor: 'pointer', padding: '0 24px', userSelect: 'none' },
  todayLink: { fontSize: 13, letterSpacing: '0.15em', textTransform: 'uppercase', color: t.textMuted, cursor: 'pointer', marginTop: 24, display: 'inline-block' },
  weekStrip: { display: 'flex', justifyContent: 'center', gap: 16, marginBottom: 40 },
  weekDay: { display: 'flex', flexDirection: 'column', alignItems: 'center', cursor: 'pointer', padding: '8px' },
  weekDayLetter: { fontSize: 12, color: t.textFaint, marginBottom: 8 },
  weekDayNum: { fontSize: 18, fontWeight: 300, marginBottom: 12, color: t.text },
  weekDayDot: { width: 6, height: 6, borderRadius: '50%', border: `1.5px solid ${t.accent}` },
  sectionLabel: { fontSize: 12, letterSpacing: '0.2em', textTransform: 'uppercase', color: t.textMuted, marginBottom: 24 },
  timeBlock: { marginBottom: 48 },
  habitRow: { display: 'flex', alignItems: 'center', padding: '16px 0', cursor: 'pointer' },
  checkbox: { width: 24, height: 24, borderRadius: '50%', border: `1.5px solid ${t.accent}`, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, cursor: 'pointer' },
  checkboxChecked: { background: t.accent },
  habitText: { flex: 1, fontSize: 18, marginLeft: 20, fontWeight: 300, color: t.text },
  habitTextDone: { color: t.textFaint, textDecoration: 'line-through' },
  habitDuration: { fontSize: 14, color: t.textFaint, marginLeft: 20, fontVariantNumeric: 'tabular-nums' },
  todoSection: { marginTop: 64, paddingTop: 48, borderTop: `1px solid ${t.border}` },
  todoInput: { width: '100%', border: 'none', outline: 'none', fontSize: 18, padding: '16px 0', fontFamily: 'inherit', background: 'transparent', fontWeight: 300, color: t.text },
  progressContainer: { marginTop: 64, display: 'flex', alignItems: 'center', gap: 20 },
  progressBar: { flex: 1, height: 2, background: t.border, position: 'relative' },
  progressFill: { position: 'absolute', left: 0, top: 0, height: '100%', background: t.accent, transition: 'width 300ms ease-out' },
  progressText: { fontSize: 14, color: t.textMuted, fontVariantNumeric: 'tabular-nums' },
  // Insights styles
  insightsHeader: { marginBottom: 64 },
  statsRow: { display: 'flex', justifyContent: 'center', gap: 32, marginBottom: 48, flexWrap: 'wrap' },
  statItem: { textAlign: 'center' },
  statRing: { position: 'relative', width: 140, height: 140, marginBottom: 20 },
  statNumber: { position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', fontSize: 32, fontWeight: 200, lineHeight: 1, color: t.text },
  statLabel: { fontSize: 12, letterSpacing: '0.2em', textTransform: 'uppercase', color: t.textMuted },
  gridContainer: { marginBottom: 80 },
  gridMonths: { display: 'flex', marginBottom: 16, paddingLeft: 32 },
  gridMonthLabel: { fontSize: 11, color: t.textFaint, letterSpacing: '0.05em' },
  gridWrapper: { display: 'flex', gap: 8 },
  gridDayLabels: { display: 'flex', flexDirection: 'column', gap: 4, paddingRight: 12, justifyContent: 'space-around' },
  gridDayLabel: { fontSize: 11, color: t.textFaintest, height: 12, display: 'flex', alignItems: 'center' },
  gridWeeks: { display: 'flex', gap: 4 },
  gridWeek: { display: 'flex', flexDirection: 'column', gap: 4 },
  gridCell: { width: 12, height: 12, borderRadius: 2 },
  gridLegend: { display: 'flex', alignItems: 'center', gap: 16, marginTop: 24, justifyContent: 'flex-end' },
  gridLegendItem: { display: 'flex', alignItems: 'center', gap: 6, fontSize: 11, color: t.textMuted },
  gridLegendBox: { width: 12, height: 12, borderRadius: 2 },
  breakdownSection: { marginBottom: 80 },
  breakdownGrid: { display: 'grid', gridTemplateColumns: '1fr', gap: 0 },
  breakdownCard: { padding: '24px 0', borderBottom: `1px solid ${t.borderLight}` },
  breakdownCardHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
  breakdownCardTitle: { fontSize: 16, fontWeight: 300, lineHeight: 1.5, color: t.text },
  breakdownCardPct: { fontSize: 16, fontWeight: 400, color: t.textMuted },
  breakdownCardBar: { display: 'none' },
  breakdownCardBarFill: { display: 'none' },
  breakdownCardStreak: { display: 'none' },
  trendContainer: { marginBottom: 80 },
  trendChart: { background: t.bgAlt, borderRadius: 8, padding: '32px', position: 'relative' },
  trendToggles: { display: 'flex', gap: 8, marginTop: 24, justifyContent: 'center' },
  trendToggle: { fontSize: 12, color: t.textMuted, cursor: 'pointer', border: 'none', background: 'none', padding: '8px 16px', fontFamily: 'inherit' },
  trendToggleActive: { color: t.text },
  weekdayHeatmap: { marginBottom: 80 },
  heatmapGrid: { display: 'flex', justifyContent: 'space-between' },
  heatmapDay: { display: 'flex', flexDirection: 'column', alignItems: 'center', padding: 16 },
  heatmapDayLabel: { fontSize: 12, fontWeight: 400, marginBottom: 8, color: t.textMuted },
  heatmapDayValue: { fontSize: 24, fontWeight: 200 },
  modalOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.4)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000, padding: 24 },
  modal: { background: t.bg, width: '100%', maxWidth: 480, maxHeight: '90vh', overflow: 'auto', padding: 40, position: 'relative', borderRadius: 12 },
  modalClose: { position: 'absolute', top: 20, right: 20, fontSize: 24, color: t.textMuted, cursor: 'pointer', border: 'none', background: 'none' },
  modalTitle: { fontSize: 13, letterSpacing: '0.15em', textTransform: 'uppercase', color: t.textMuted, marginBottom: 28 },
  modalInput: { width: '100%', border: 'none', borderBottom: `2px solid ${t.border}`, outline: 'none', fontSize: 20, padding: '16px 0', fontFamily: 'inherit', marginBottom: 28, background: 'transparent', color: t.text },
  modalLabel: { fontSize: 12, letterSpacing: '0.12em', textTransform: 'uppercase', color: t.textMuted, marginBottom: 16, display: 'block' },
  pillGroup: { display: 'flex', flexWrap: 'wrap', gap: 10, marginBottom: 28 },
  pill: { padding: '10px 18px', fontSize: 14, border: `1.5px solid ${t.accent}`, cursor: 'pointer', fontFamily: 'inherit', background: 'transparent', borderRadius: 6, color: t.text },
  pillSelected: { background: t.accent, color: t.accentText },
  dayPill: { width: 44, height: 44, padding: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: '50%', fontSize: 14 },
  modalButton: { width: '100%', padding: '18px 28px', fontSize: 16, background: t.accent, color: t.accentText, border: 'none', cursor: 'pointer', fontFamily: 'inherit', marginTop: 28, borderRadius: 8 },
  archiveButton: { width: '100%', padding: '14px 24px', fontSize: 14, background: 'transparent', color: t.textMuted, border: 'none', cursor: 'pointer', fontFamily: 'inherit', marginTop: 16 },
  settingsSection: { marginBottom: 36, paddingBottom: 36, borderBottom: `1px solid ${t.border}` },
  sliderContainer: { display: 'flex', alignItems: 'center', gap: 20 },
  slider: { flex: 1, height: 4, WebkitAppearance: 'none', appearance: 'none', background: t.border, outline: 'none', cursor: 'pointer', borderRadius: 2 },
  sliderValue: { fontSize: 28, fontWeight: 100, minWidth: 70, textAlign: 'right', color: t.text },
  settingsNote: { fontSize: 14, color: t.textMuted, marginTop: 16, lineHeight: 1.6 },
  darkModeToggle: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '16px 0' },
  darkModeSwitch: { width: 52, height: 28, borderRadius: 14, background: t.border, position: 'relative', cursor: 'pointer', transition: 'background 200ms' },
  darkModeSwitchActive: { background: t.accent },
  darkModeSwitchKnob: { position: 'absolute', top: 3, left: 3, width: 22, height: 22, borderRadius: '50%', background: t.bg, transition: 'transform 200ms', boxShadow: '0 1px 3px rgba(0,0,0,0.2)' },
  darkModeSwitchKnobActive: { transform: 'translateX(24px)' },
  // Stendig Calendar styles
  stendigCalendar: { userSelect: 'none' },
  stendigHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 36 },
  stendigMonth: { fontSize: 14, letterSpacing: '0.2em', textTransform: 'uppercase', color: t.text, fontWeight: 400 },
  stendigNavArrow: { fontSize: 24, fontWeight: 200, color: t.textFaint, cursor: 'pointer', padding: 4, lineHeight: 1 },
  stendigGrid: { display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: 4 },
  stendigDayHeader: { fontSize: 11, letterSpacing: '0.15em', textTransform: 'uppercase', color: t.textFaintest, textAlign: 'center', paddingBottom: 16 },
  stendigDay: { aspectRatio: '1', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 16, fontWeight: 300, color: t.text, cursor: 'pointer', position: 'relative' },
  stendigDayToday: { fontWeight: 500 },
  stendigDaySelected: { background: t.accent, color: t.accentText, borderRadius: '50%' },
  stendigDayOtherMonth: { color: t.textFaintest },
  stendigStrikeX: { position: 'absolute', top: '50%', left: '50%', width: '60%', height: 1.5, background: t.accent },
  // Timeline styles
  timelineContainer: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' },
  timelineHeader: { marginBottom: 32 },
  timelineTitle: { fontSize: 11, letterSpacing: '0.2em', textTransform: 'uppercase', color: t.textMuted, marginBottom: 8 },
  timelineDate: { fontSize: 22, fontWeight: 200, color: t.text },
  timelineScroll: { flex: 1, overflowY: 'auto', marginRight: -8, paddingRight: 8 },
  timelineHours: { position: 'relative' },
  timelineHour: { display: 'flex', height: 48, borderTop: `1px solid ${t.borderLight}` },
  timelineHourLabel: { width: 44, fontSize: 12, color: t.textFaintest, paddingTop: 4, flexShrink: 0, fontVariantNumeric: 'tabular-nums' },
  timelineHourContent: { flex: 1, position: 'relative' },
  timelineBlockBar: { position: 'absolute', left: 0, right: 0, borderLeft: `2px solid ${t.accent}`, paddingLeft: 12, paddingTop: 6 },
  timelineBlockLabel: { fontSize: 10, letterSpacing: '0.1em', textTransform: 'uppercase', color: t.textMuted, marginBottom: 6 },
  timelineHabit: { fontSize: 13, lineHeight: 1.7, color: t.textSecondary },
  timelineHabitDone: { color: t.textFaintest, textDecoration: 'line-through' },
  timelineNowLine: { position: 'absolute', left: 44, right: 0, height: 2, background: t.accent, zIndex: 10, pointerEvents: 'none' },
  timelineNowDot: { position: 'absolute', left: 36, width: 8, height: 8, borderRadius: '50%', background: t.accent, transform: 'translateY(-3px)', zIndex: 10 },
  timelineSummary: { marginTop: 'auto', paddingTop: 24, borderTop: `1px solid ${t.borderLight}` },
  timelineSummaryValue: { fontSize: 48, fontWeight: 100, lineHeight: 1, marginBottom: 6, color: t.text },
  timelineSummaryLabel: { fontSize: 10, letterSpacing: '0.2em', textTransform: 'uppercase', color: t.textMuted },
  // Mobile styles
  mobileContainer: { padding: '20px 24px 110px', minHeight: '100vh', background: t.bg, color: t.text, fontFamily: "'Instrument Sans', system-ui, sans-serif" },
  mobileHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 28 },
  mobileCalendarToggle: { padding: '12px 20px', fontSize: 14, border: `1.5px solid ${t.border}`, background: 'transparent', borderRadius: 24, cursor: 'pointer', fontFamily: 'inherit', display: 'flex', alignItems: 'center', gap: 8, color: t.text },
  mobileCalendarDropdown: { position: 'fixed', top: 0, left: 0, right: 0, background: t.bg, padding: '24px', boxShadow: '0 4px 24px rgba(0,0,0,0.12)', zIndex: 100, maxHeight: '75vh', overflow: 'auto' },
  mobileNav: { position: 'fixed', bottom: 0, left: 0, right: 0, background: t.bg, borderTop: `1px solid ${t.border}`, display: 'flex', justifyContent: 'space-around', padding: '16px 0 28px', zIndex: 100 },
  mobileNavItem: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 6, border: 'none', background: 'none', cursor: 'pointer', fontFamily: 'inherit', padding: '10px 20px', color: t.text },
  mobileNavIcon: { fontSize: 24 },
  mobileNavLabel: { fontSize: 12, letterSpacing: '0.08em', textTransform: 'uppercase' },
  mobileDateHeader: { textAlign: 'center', marginBottom: 28 },
  mobileDayNumber: { fontSize: 96, fontWeight: 100, lineHeight: 1, position: 'relative', display: 'inline-block', color: t.text },
  mobileStrikeX: { position: 'absolute', top: '50%', left: '50%', width: '120%', height: 3, background: t.accent },
  mobileStatsRow: { display: 'flex', justifyContent: 'space-around', padding: '20px 0', marginBottom: 28, borderTop: `1px solid ${t.border}`, borderBottom: `1px solid ${t.border}` },
  mobileStatItem: { textAlign: 'center' },
  mobileStatValue: { fontSize: 28, fontWeight: 200, color: t.text },
  mobileStatLabel: { fontSize: 11, letterSpacing: '0.1em', textTransform: 'uppercase', color: t.textMuted },
  // Manage habits styles
  manageHabitRow: { display: 'flex', alignItems: 'center', padding: '16px 0', borderBottom: `1px solid ${t.borderLight}` },
  manageHabitText: { flex: 1, fontSize: 16, color: t.text },
  manageHabitMeta: { fontSize: 14, color: t.textMuted, marginLeft: 16 },
  manageHabitActions: { display: 'flex', gap: 10, marginLeft: 16 },
  manageActionBtn: { width: 36, height: 36, border: `1.5px solid ${t.border}`, background: 'transparent', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 16, color: t.textSecondary, borderRadius: 6 },
  manageBlockSection: { marginBottom: 36 },
  backLink: { fontSize: 14, color: t.textMuted, cursor: 'pointer', marginBottom: 28, display: 'inline-flex', alignItems: 'center', gap: 8 },
  // Auth styles
  authContainer: { minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: t.bg, fontFamily: "'Instrument Sans', system-ui, sans-serif" },
  authCard: { textAlign: 'center', padding: 48 },
  authTitle: { fontSize: 48, fontWeight: 100, marginBottom: 8, color: t.text },
  authSubtitle: { fontSize: 14, color: t.textMuted, marginBottom: 48, letterSpacing: '0.1em' },
  authButton: { display: 'inline-flex', alignItems: 'center', gap: 12, padding: '16px 32px', fontSize: 16, background: t.bg, color: t.text, border: `1.5px solid ${t.border}`, borderRadius: 8, cursor: 'pointer', fontFamily: 'inherit', transition: 'all 200ms' },
  authDivider: { margin: '32px 0', color: t.textMuted, fontSize: 12 },
  authSkip: { fontSize: 14, color: t.textMuted, cursor: 'pointer', textDecoration: 'underline' },
});
